In [7]:
# Generate 5 random values between 0 and 1 representing normalized scores using
import numpy as np
np1 = np.random.rand(5)
print(np1)
# Generate 5 random values from a normal distribution using 
np2 = np.random.randn(5)
print(np2)

[0.18534519 0.28211356 0.28556919 0.02466093 0.09827705]
[ 1.828213    0.17429864  0.66595445  0.02470223 -0.9236496 ]


In [9]:
# Create a 3×4 array of random integers between 35 and 100 using
import numpy as np
np1 = np.random.randint(35,100,(3,4))
print(np1)

[[91 82 74 48]
 [40 65 67 66]
 [67 87 79 74]]


In [11]:
# Given a list of student IDs Randomly select 2 students using
import numpy as np
np1=np.array([101, 102, 103, 104, 105])
print(np.random.choice(np1,2))          # (np.random.choice(arr, size=2))


[105 101]


In [13]:
# Fix the Random Output
# Set a random seed value 10
import numpy as np
np.random.seed(10)
# Generate 3 random values using
# Observe that output remains the same every time
np1 = np.random.rand(3)
print(np1)


[0.77132064 0.02075195 0.63364823]


In [21]:
# Basic Indexing & Slicing
# Using the array [10, 20, 30, 40, 50, 60]
import numpy as np
np1 = np.array([10, 20, 30, 40, 50, 60])
# Print the 3rd element
print(np1[2])
# Print elements from index 1 to 4
print(np1[1:5])
# Print the last element
print(np1[-1])
# Print every second element
print(np1[::2])
# Reverse the array
print(np1[::-1])

30
[20 30 40 50]
60
[10 30 50]
[60 50 40 30 20 10]
