In [10]:
#Create a 1D array containing marks of 5 students: 60, 70, 80, 90, 100
import numpy as np
np1 = np.array([60,70,80,90,100])
#Create a 2D array representing marks of 2 students in 3 subjects
np2 = np.array([[85,95,98],[90,94,97]])
print(np2)
#Create a 3D array representing marks of 2 classes, each with 2 students and 3 subjects
np3 = np.array([[[85,95,98],[90,94,97]],
                [[89,98,99],
                 [87,88,89]]
               ])
print(np3)
print(np3.ndim
     )
#Task 2: Check Array Attributes
# shape
print(np2.shape)
# ndim
print(np2.ndim)
# dtype
print(np2.dtype)
# size
print(np2.size)

[[85 95 98]
 [90 94 97]]
[[[85 95 98]
  [90 94 97]]

 [[89 98 99]
  [87 88 89]]]
3
(2, 3)
2
int32
6


In [25]:
# Create a 3×4 array of zeros
import numpy as np
npzero = np.zeros((3,4))
print(npzero)
#Create a 2×3 array of ones
npones=np.ones((2,3))
print(npones)
#Create a 3×3 array filled with value 5
npfull=np.full((3,3),5)
print(npfull)
# Create a 4×4 identity matrix
npiden = np.eye((4))
print(npiden)
# Create a diagonal matrix with values
npdia = np.diag([10, 20, 30, 40])
print(npdia)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


In [30]:
import numpy as np
# Create an array from 10 to 50 with step 10
npara = np.arange(10,50,10)
print(npara)
#Create 5 evenly spaced values between 0 and 100
nplin = np.linspace(0,100,5)
print(nplin)

[10 20 30 40]
[  0.  25.  50.  75. 100.]
