In [11]:
#Perform: Total marks (addition), Difference (term2 − term1),Increase percentage using multiplication by 1.05
import numpy as np
marks_term1 = np.array([60, 70, 80, 90])
marks_term2 = np.array([65, 75, 85, 95])
Total = marks_term1 + marks_term2
print(Total)
diff = marks_term2 - marks_term1
print(diff)
mark_increase_term1 = marks_term1 * 1.05
mark_increase_term2 = marks_term2 * 1.05
print(mark_increase_term1)
print(mark_increase_term2)
#From the total marks array: Find marks greater than 150 & Find marks between 140 and 170
print(Total[Total>150])
print(Total[(Total>=140) & (Total<=170)])
#From the total marks array: Find Sum,Mean,Maximum,Minimum,Standard deviation
print(Total.sum())
print(Total.mean())
print(Total.max())
print(Total.min())
print(Total.std())



[125 145 165 185]
[5 5 5 5]
[63.  73.5 84.  94.5]
[68.25 78.75 89.25 99.75]
[165 185]
[145 165]
620
155.0
185


In [16]:
#Create a 2×3 array of marks: Column-wise sum and Row-wise mean
import numpy as np
arr = np.array([[70, 80, 90],
                [60, 75, 85]])
print(arr)
print(arr.sum(axis=0))
print(arr.sum(axis=1))

[[70 80 90]
 [60 75 85]]
[130 155 175]
[240 220]


In [21]:
#shape, ndim, size, dtype, Reshape it into 2×3,Convert it back to 1D using ravel()
import numpy as np
np1 = np.array([1, 2, 3, 4, 5, 6])
print(np1.ndim)
print(np1.size)
print(np1.dtype)
np2 = (np1.reshape(2,3))
print(np2)
np1 = np2.ravel()
print(np1)


1
6
int32
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
